import {Types} from 'mongoose';
import {field, document, transient} from 'nodedata/mongoose/decorators';
import {Strict} from 'nodedata/mongoose/enums/';
import {onetomany, manytoone, manytomany, onetoone, promisable, IPromisableFetchParam} from 'nodedata/core/decorators';

@document({ name: 'teacher', strict: Strict.false })
export class teacherModel {

    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    isSinger: boolean;

    @field()
    name: string;

}

export default teacherModel;